spring:
  thymeleaf:
    # 缓冲配置
    cache: false
    # 检查模板配置
    check-template: true
    # 检查模板位置是否正确（默认值:true）
    check-template-location: true
    #Content-Type的值（默认值：text/html）
    content-type: text/html
    # 开启MVC Thymeleaf视图解析（默认值：true）
    enabled: true
    # 模板编码
    encoding: UTF-8
    # 要被排除在解析之外的视图名称列表，用逗号分隔
#    excluded-view-names:
    # 要运用于模板之上的模板模式。另见StandardTemplate-ModeHandlers(默认值：HTML5)
    mode: LEGACYHTML5
    # 在构建URL时添加到视图名称前的前缀（默认值：classpath:/templates/）
    prefix: classpath:/templates/
    # 在构建URL时添加到视图名称后的后缀（默认值：.html）
    suffix: .html
    # Thymeleaf模板解析器在解析器链中的顺序。默认情况下，它排第一位。顺序从1开始，只有在定义了额外的TemplateResolver Bean时才需要设置这个属性。
#    template-resolver-order:
    # 可解析的视图名称列表，用逗号分隔
#    view-names: